# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-10-30 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssetManagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource1',
            name='UserCategory',
            field=models.CharField(default='\u5185\u90e8\u7528\u6237', max_length=50, verbose_name='\u7528\u6237\u7c7b\u578b'),
        ),
        migrations.AlterField(
            model_name='resource1',
            name='ResourceType',
            field=models.CharField(max_length=50, verbose_name='\u8d44\u6e90\u7c7b\u578b'),
        ),
    ]
